CREATE TABLE all_lab_orders
(
    patient_id                   VARCHAR(50),
    emr_id                       VARCHAR(50),
    loc_registered               VARCHAR(255),
    unknown_patient              VARCHAR(11),
    gender                       VARCHAR(50),
    age_at_enc                   FLOAT,
    order_number                 VARCHAR(50),
    order_reason                 VARCHAR(255),
    Lab_ID                       VARCHAR(50),
    orderable                    VARCHAR(255),
    status                       VARCHAR(50),
    orderer                      VARCHAR(255),
    orderer_provider_type        VARCHAR(50),
    order_datetime               DATETIME,
    ordering_location            TEXT,
    visit_id                     VARCHAR(50),
    visit_location               VARCHAR(255),
    facility                     VARCHAR(255),
    urgency                      VARCHAR(50),
    specimen_collection_datetime DATETIME,
    collection_date_estimated    VARCHAR(11),
    test_location                VARCHAR(225),
    result_date                  DATETIME
);
