CREATE TABLE all_patients
(
emr_id                    varchar(50),  
hiv_emr_id                varchar(50),  
dossier_id                varchar(50),  
patient_id                varchar(100), 
mothers_first_name        varchar(255), 
country                   varchar(255), 
department                varchar(255), 
commune                   varchar(255), 
section_communale         varchar(255), 
locality                  varchar(255), 
telephone_number          varchar(50),  
civil_status              varchar(255), 
occupation                varchar(255), 
reg_location              varchar(50),  
registration_date         date,         
date_registration_entered datetime,     
user_entered              varchar(50),  
first_encounter_date      date,         
last_encounter_date       date,         
name                      varchar(50),  
family_name               varchar(50),  
dob                       date,         
dob_estimated             bit,          
gender                    varchar(2),   
dead                      bit,          
death_date                date,         
cause_of_death            varchar(100)  
)
;
