CREATE TABLE all_medication_dispensing
(
form varchar(10),
patient_id varchar(50),
emr_id varchar(50),
encounter_id varchar(50),
encounter_datetime datetime,
encounter_location varchar(100),
datetime_entered datetime,
creator varchar(30),
encounter_provider varchar(30),
drug_name varchar(500),
drug_openboxes_code int,
duration int,
duration_unit varchar(20),
quantity_per_dose float,
dose_unit varchar(50),
frequency varchar(50),
quantity_dispensed int,
quantity_unit varchar(30),
order_id int, 
instructions text,
index_asc int,
index_desc int
);
