CREATE TABLE  dim_patients (
emr_id varchar(50),
hiv_emr_id varchar(50),
dossier_number varchar(50),
patient_id int, 
reg_location varchar(50),
reg_date date,
fist_encounter_date date,
last_encounter_date date, 
name varchar(50),
family_name varchar(50),
dob date,
dob_estimated bit,
gender varchar(2),
dead bit,
death_date date,
cause_of_death varchar(100),
ncd_enrolled bit,
ncd_last_encounter_date date,
echo_enrolled bit,
echo_last_encounter_date date,
hiv_enrolled bit,
hiv_last_encounter_date date
);