CREATE TABLE echo_summary_table (
patient_id integer, 
emrid varchar(50), 
age int,
sex char(1),
department varchar(50),
commune varchar(50),
section_communal varchar(50),
locality varchar(50),
heart_failure boolean,
echo_date_most_recent date,
echo_date_prior date,
total_echos int,
lvsf_most_recent varchar(50),
lvsf_prior varchar(50),
lvsf_change varchar(30),
mitral_stenosis boolean DEFAULT FALSE,
nyha_class_most_recent varchar(50),
cardiomyopathy boolean,
beta_blocker_atenolol boolean,
beta_blocker_metoprolol boolean,
beta_blocker_carvedilol boolean,
ace_inhibitor boolean,
penicillin boolean,
spironolactone boolean,
hydralazine_hydrochloride boolean,
isosorbide_dinitrate boolean,
diuretic boolean,
calcium_channel_blocker boolean,
follow_up_echo boolean,
bp_systolic_most_recent int,
bp_diastolic_most_recent int,
ncd_comorbidity boolean,
dm1 boolean DEFAULT FALSE,
dm2 boolean DEFAULT FALSE,
hypertension boolean,
asthma boolean,
sickle_cell boolean,
copd boolean
);