create table ncd_patient_table
(
emr_id varchar(50),
birthdate date,
sex char(1),
department varchar(50),
commune varchar(50),
ncd_enrollment_date date,
ncd_first_encounter_date date,
ncd_enrollment_location varchar(50),
ncd_current_location varchar(50), 
htn bit,
diabetes bit,
respiratory bit,
epilepsy bit,
heart_failure bit,
cerebrovascular_accident bit,
renal_failure bit,
liver_failure bit,
rehabilitation bit,
sickle_cell bit,
other_ncd bit,
dm_type varchar(50),
heart_failure_category varchar(50),
cardiomyopathy varchar(50),
nyha_class varchar(50),
heart_failure_improbable bit,
ncd_status varchar(50),
ncd_status_date date,
deceased bit,
date_of_death date
);
