name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-sonatype.yml@main
    with:
      image_name: partnersinhealth/zl-etl
      docker_context: target/docker
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-zl-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-zl-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: zl-ci
      puppet-manifest: petl
      run-etl: true
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-hiv-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-hiv-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/run-petl-via-runner.yml@main
    with:
      runner-label: appclstr-01
      instance: hiv-ci
      notify_ci_dashboard: true
    secrets: inherit
