name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-versions:
    if: github.repository_owner == 'PIH'
    permissions:
      contents: write
    concurrency:
      group: update-versions-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/update-versions.yml@main
    secrets: inherit

  build-and-publish:
    if: github.repository_owner == 'PIH'
    needs: update-versions
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-sonatype.yml@main
    with:
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-zl-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-zl-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: zl-ci
      puppet-manifest: petl
      run-etl: true
      notify_ci_dashboard: true
    secrets: inherit
