name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-versions:
    if: github.repository_owner == 'PIH'
    permissions:
      contents: write
    concurrency:
      group: update-versions-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/update-versions.yml@main
    secrets: inherit

  build-and-publish:
    if: github.repository_owner == 'PIH'
    needs: update-versions
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-sonatype.yml@main
    secrets: inherit

  deploy-to-zl-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-to-zl-ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Deploy to zl-ci
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-ETLDEPLOYZLETLTOZLCI'
          method: 'POST'
          bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
          customHeaders: '{"Accept": "application/json"}'
          retry: 60
          retryWait: 60000
          ignoreStatusCodes: 400
